<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go To MultiPayment</name>
   <tag></tag>
   <elementGuidId>0fbf1360-6339-4cc8-9f73-e3fcea3f3bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top']/section[2]/div/div/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edee2ab4-c61a-4d6c-9f23-01e0f4a712a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/uangku/multipayment</value>
      <webElementGuid>4ea9c847-f46e-4cfa-abdc-d242ec9713f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-main btn-round-full</value>
      <webElementGuid>cc0a9290-9a39-4bfd-a3f7-bcea86dda084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go To MultiPayment</value>
      <webElementGuid>2b69d3d7-c6da-4c0f-80cb-c31c516eefd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/section[@class=&quot;features&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;feature-block d-lg-flex&quot;]/div[@class=&quot;feature-item mb-5 mb-lg-0&quot;]/a[@class=&quot;btn btn-main btn-round-full&quot;]</value>
      <webElementGuid>a65bc9d5-d142-4cd7-80d4-6d5fb4ebd8c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top']/section[2]/div/div/div/div/div[2]/a</value>
      <webElementGuid>528d919e-9c13-491f-93d3-04a32b464e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go To MultiPayment')]</value>
      <webElementGuid>06437389-d1ac-4321-8743-3c862a1e83ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MultiPayment'])[2]/following::a[1]</value>
      <webElementGuid>58188e8e-095f-40e6-a09d-706eb2cc2f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go To Transaction'])[1]/following::a[1]</value>
      <webElementGuid>bc6b275c-f5a6-4c9e-8932-b7f976e35489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer via Friends'])[1]/preceding::a[1]</value>
      <webElementGuid>20f61f4a-69bc-4ad8-a5eb-f2c5796a749d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction via Friends'])[1]/preceding::a[1]</value>
      <webElementGuid>1bc9da6f-85b8-4489-a44e-378166484a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go To MultiPayment']/parent::*</value>
      <webElementGuid>212380ab-d658-436d-84be-1de340dc55c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/uangku/multipayment')])[2]</value>
      <webElementGuid>8e28094b-5d47-4275-9a7c-62ccb0f3dce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div[2]/a</value>
      <webElementGuid>885fa477-cf90-4f91-8c55-92fbecff3383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/uangku/multipayment' and (text() = 'Go To MultiPayment' or . = 'Go To MultiPayment')]</value>
      <webElementGuid>f4b10ca0-a018-468f-8f59-fbe6cc3ec82b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
